# Generated by Django 5.2.1 on 2025-06-09 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_notifications'),
        ('posts', '0006_alter_posts_id'),
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='users.userregistration'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
    ]
