# Generated by Django 5.2.1 on 2025-06-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_remove_comment_like_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='liked_by',
        ),
    ]
